name: test script
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:
jobs:
  build:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v2
    - name: test script
      run: |
        python /home/openeuler/test.py

    - name: Debug Environment
      run: |
        echo "Running on openeuler..."
        cat /etc/os-release