name: print id
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:


jobs:
  upload-to-openlibing:
    runs-on: ubuntu-latest

    steps:
      - name: pirnt 1
        run: env | sort

      - name: steps
        run: steps | sort

  print-env:
    runs-on: ubuntu-latest
    steps:
      - name: pirnt 1
        run: env | sort

      - name: pirnt 2
        run: env | sort

      - name: pirnt 5
        run: env | sort

  print-env2:
    runs-on: ubuntu-latest
    steps:
      - name: pirnt 1
        run: env | sort
